### ISSUE TITLE
ping監視の設定

### ISSUE THREAD

**Issue by sorah** [ruby-no-kai/rubykaigi-nw#66]
routing protocol による経路切り替えが仕様として上手くいかない部分となんかたまに狂う部分があるので ping 監視をしておきたい

## public IP

- v6: ge-0-0-23.csw-01.venue.rubykaigi.net
- v6: ge-0-0-23.csw-02.venue.rubykaigi.net
- v6: vlan-2046.csw-01.venue.rubykaigi.net
- v6: vlan-2044.csw-02.venue.rubykaigi.net
- v4: nat.gw-01.venue.rubykaigi.net
- v4: nat.gw-02.venue.rubykaigi.net

## private IP

`lo0.*.venue.rubykaigi.net` すべて

**Comment by hanazuki** [comment]
v6を監視するため & パケロス率/レイテンシの細かいデータを取るためにEC2にcloudproberを置く．余裕があったら適当なx86箱でvenue用インスタンスも作る

**Comment by hanazuki** [comment]
あとは監視ルールを書くだけ

**Comment by hanazuki** [comment]
memo: maxTargetsPerProbeの設定
